[theme]
base = "dark"
primaryColor = "#2962FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E2E"
textColor = "#FAFAFA"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
